# Yarn PnP configuration
# Using Yarn's Plug'n'Play for faster, more reliable package management

nodeLinker: pnp

# Yarn version (using latest stable)
# Sorry, copilot, I had to comment this 'cause it doesn't work for some reason. But we're working fine without it. Maybe we'd get an improvement with it? Let me know if you notice.
# yarnPath: .yarn/releases/yarn-4.5.3.cjs

# Cache and install settings
enableGlobalCache: false
enableTelemetry: false

# Package resolution
packageExtensions:
  "@types/three@*":
    dependencies:
      three: "*"

# Development conveniences  
preferInteractive: true
