[package]
name = "steam-brick-and-mortar-desktop"
version = "0.1.0"
edition = "2021"

[package.metadata]

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target."cfg(windows)".dependencies]
parselnk = "0.1.1"
winreg = "0.56.0"
